
CREATE TABLE daily_81102 (
StateCode varchar(100),
CountyCode varchar(100),
SiteNum varchar(100),
ParameterCode varchar(100),
POC int,
Latitude numeric(10,6),
Longitude numeric(10,6),
Datum varchar(100),
ParameterName varchar(100),
SampleDuration varchar(100),
PollutantStandard varchar(100),
DateLocal date,
UnitsOfMeasure varchar(100),
EventType varchar(100),
ObservationCount int,
ObservationPercent numeric(10,5),
ArithmeticMean int,
FirstMaxVal int,
FirstMaxHour int,
AQI int,
MethodCode varchar(100),
MethodName varchar(100),
LocalSiteName varchar(100),
Address varchar(100),
StateName varchar(100),
CountyName varchar(100),
CityName varchar(100),
CBSAName varchar(100),
DateOfLastChange date
);



CREATE TABLE daily_44201 (
StateCode varchar(100),
CountyCode varchar(100),
SiteNum varchar(100),
ParameterCode varchar(100),
POC int,
Latitude numeric(10,6),
Longitude numeric(10,6),
Datum varchar(100),
ParameterName varchar(100),
SampleDuration varchar(100),
PollutantStandard varchar(100),
DateLocal date,
UnitsOfMeasure varchar(100),
EventType varchar(100),
ObservationCount int,
ObservationPercent numeric(10,5),
ArithmeticMean numeric(10,5),
FirstMaxVal numeric(10,5),
FirstMaxHour int,
AQI int,
MethodCode varchar(100),
MethodName varchar(100),
LocalSiteName varchar(100),
Address varchar(100),
StateName varchar(100),
CountyName varchar(100),
CityName varchar(100),
CBSAName varchar(100),
DateOfLastChange date
);
